# Generated by Django 5.2.7 on 2025-12-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_author_alter_review_options_remove_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
