# Generated by Django 5.2.7 on 2025-12-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_admin_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
