# Generated by Django 5.2.7 on 2025-11-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_promotion_recommendationengine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='expiry_date',
            new_name='expire_date',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.PositiveIntegerField(),
        ),
    ]
