# Generated by Django 5.2.7 on 2025-12-16 14:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_promocode_alter_order_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voucher_type', models.CharField(choices=[('PERCENT', 'Giảm theo %'), ('FIXED', 'Giảm tiền cố định')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Giá trị giảm (% hoặc số tiền)', max_digits=12)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Đơn hàng tối thiểu để áp dụng', max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Số lượt sử dụng còn lại')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='promotion',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK', 'Chuyển khoản ngân hàng'), ('QR', 'Chuyển khoản QR')], default='COD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Mã nhập tay', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.promocode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tổng tiền sau giảm', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tổng tiền gốc', max_digits=12),
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_users', to='order.voucher')),
            ],
            options={
                'unique_together': {('user', 'voucher')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user_voucher',
            field=models.ForeignKey(blank=True, help_text='Voucher user đã chọn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.uservoucher'),
        ),
    ]
