# Generated by Django 5.2.7 on 2025-12-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_voucher_remove_order_promotion_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK', 'Chuyển khoản ngân hàng')], default='COD', max_length=10),
        ),
    ]
