# Generated by Django 5.2.7 on 2026-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Số tiền giảm tối đa (0 = không giới hạn)', max_digits=10, null=True),
        ),
    ]
